#############################################EE_frame_name###################################
# robot configs
################################################################################
sim_robot_variables:
  urdf_filename: "/models/cassie/urdf/cassie_v4.urdf"
  mesh_foldername: "/models/cassie/meshes"
  use_fixed_base: True

  base_name: "pelvis"
  joint_names: [
    "LeftHipRoll", "LeftHipYaw", "LeftHipPitch", "LeftKneePitch", "LeftShinPitch", "LeftTarsusPitch", "LeftAchillesSpring", "LeftFootPitch", "RightHipRoll", "RightHipYaw", "RightHipPitch", "RightKneePitch", "RightShinPitch", "RightTarsusPitch", "RightAchillesSpring", "RightFootPitch"
  ]  # pinocchio order
  limb_names: ["left_leg", "right_leg"]
  limb_endeff_names: ["leftfoot","rightfoot"]
  limb_endeff_joint_names: ["LeftFootPitch", "RightFootPitch"]
  limb_endeff_frame_names: ["LeftFootPitch", "RightFootPitch"]

  base_init_pos: [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.] # posture
  base_init_vel: [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]
  joint_init_pos: [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]
  joint_init_vel: [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]


################################################################################
# control configs
################################################################################
control_variables:
  joint_names: [
    "LeftHipRoll", "LeftHipYaw", "LeftHipPitch", "LeftKneePitch", "LeftShinPitch", "LeftTarsusPitch", "LeftAchillesSpring", "LeftFootPitch", "RightHipRoll", "RightHipYaw", "RightHipPitch", "RightKneePitch", "RightShinPitch", "RightTarsusPitch", "RightAchillesSpring", "RightFootPitch"
  ]  # pinocchio order
  joint_des_pos: [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]
