################################################################################
# robot configs
################################################################################
sim_robot_variables:
  urdf_filename: "/models/custom/custom_lower_body.urdf"
  mesh_foldername: "/models/poppy/meshes"
  use_fixed_base: True

  base_name: "z_base_to_r_hip_yaw"
  joint_names: [  "z_base_to_l_hip_yaw", "l_hip_yaw_to_pitch", "l_hip_pitch_to_roll", "l_upper_leg_to_knee", "l_lower_leg_to_ankle", "z_base_to_r_hip_yaw", "r_hip_yaw_to_pitch", "r_hip_pitch_to_roll", "r_upper_leg_to_knee", "r_lower_leg_to_ankle"
  ]  # pinocchio order
  limb_names: ["left_leg", "right_leg"]
  limb_endeff_names: ["l_foot", "r_foot"]
  limb_endeff_joint_names: ["l_foot_end_effector", "r_foot_end_effector"]
  limb_endeff_frame_names: ["l_foot_end_effector", "r_foot_end_effector"]

  base_init_pos: [1., 1., 1., 0., 0., 0., 1.] # posture
  base_init_vel: [0., 0., 0., 0., 0., 0.]
  joint_init_pos: [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]
  joint_init_vel: [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]


################################################################################
# control configs
################################################################################
control_variables:
  joint_names: [ "z_base_to_l_hip_yaw", "l_hip_yaw_to_pitch", "l_hip_pitch_to_roll", "l_upper_leg_to_knee", "l_lower_leg_to_ankle", "z_base_to_r_hip_yaw", "r_hip_yaw_to_pitch", "r_hip_pitch_to_roll", "r_upper_leg_to_knee", "r_lower_leg_to_ankle"
  ]  # pinocchio order
  joint_des_pos: [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]
