################################################################################
# robot configs
################################################################################
sim_robot_variables:
  urdf_filename: "/models/project_humanoid_robot/urdf/full_robot_sphere_ee.urdf"
  mesh_foldername: "/models/our_robot/meshes"
  use_fixed_base: True

  base_name: left_shoulder_socket
  
  joint_names: ['left_ankle-2', 'left_ankle-1', 'left_knee', 'left_hip_pitch', 'left_hip_yaw', 'left_hip_roll', 'left_shoulder_roll', 'left_shoulder_yaw', 'left_shoulder_pitch', 'left_elbow', 'left_wrist_1', 'left_wrist_2', 'right_hip_roll', 'right_hip_yaw', 'right_hip_pitch', 'right_knee', 'right_ankle-1', 'right_ankle-2', 'right_shoulder_roll', 'right_shoulder_yaw', 'right_shoulder_pitch', 'right_elbow', 'right_wrist_1', 'right_wrist_2']  # pinocchio order
  limb_names: ["left_leg", "left_arm", "right_arm", "right_leg", "torso"]
  limb_endeff_names: ["left_foot", "left_hand", "right_hand", "right_foot", "torso"]
  limb_endeff_joint_names: ["left_ankle-2", "left_palm", "right_ankle-2", "right_palm", "torso_centre_joint"]
  limb_endeff_frame_names: ["left_foot", "left_hand", "right_foot", "right_hand", "torso_centre"]

  base_init_pos: [0., 0., .15, 0., 0., 0., 1.] # posture
  base_init_vel: [0., 0., 0., 0., 0., 0.]
  joint_init_pos: [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]
  joint_init_vel: [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]


################################################################################
# control configs
################################################################################
control_variables:
  joint_names: ['left_ankle-2', 'left_ankle-1', 'left_knee', 'left_hip_pitch', 'left_hip_yaw', 'left_hip_roll', 'left_shoulder_roll', 'left_shoulder_yaw', 'left_shoulder_pitch', 'left_elbow', 'left_wrist_1', 'left_wrist_2', 'right_hip_roll', 'right_hip_yaw', 'right_hip_pitch', 'right_knee', 'right_ankle-1', 'right_ankle-2', 'right_shoulder_roll', 'right_shoulder_yaw', 'right_shoulder_pitch', 'right_elbow', 'right_wrist_1', 'right_wrist_2']  # pinocchio order
  joint_des_pos: [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]
