################################################################################
# simulation configs
################################################################################
sim_robot_variables:
  urdf_filename: "/models/AliengoVx300/AliengoVx300.urdf"

  use_fixed_base: False

  base_name: "trunk"
  joint_names: [
    "FL_hip_joint", "FL_thigh_joint", "FL_calf_joint", 
    "FR_hip_joint", "FR_thigh_joint", "FR_calf_joint", 
    "RL_hip_joint", "RL_thigh_joint", "RL_calf_joint", 
    "RR_hip_joint", "RR_thigh_joint", "RR_calf_joint", 
    "waist",  "shoulder", "elbow", "wrist_angle", "wrist_rotate",
  ]  # pinocchio order
  limb_names: ["FL", "FR", "RL", "RR", "vx300"]
  limb_endeff_names: ["FL_foot", "FR_foot", "RL_foot", "RR_foot", "vx300/ee_gripper_link"]

  base_init_pos: [0., 0., 0.40, 0., 0., 0., 1.] # posture
  base_init_vel: [0., 0., 0., 0., 0., 0.]
  joint_init_pos: [0., 0.75, -1.5, 
                   0., 0.75, -1.5, 
                   0., 0.75, -1.5, 
                   0., 0.75, -1.5,
                   0., -0.7, 1.3, -0.6, 0.,]
  joint_init_vel: [0., 0., 0., 
                   0., 0., 0., 
                   0., 0., 0., 
                   0., 0., 0., 
                   0., 0., 0., 0., 0.,]


################################################################################
# control configs
################################################################################
control_variables:
  joint_names: [
    "FL_hip_joint", "FL_thigh_joint", "FL_calf_joint", 
    "FR_hip_joint", "FR_thigh_joint", "FR_calf_joint", 
    "RL_hip_joint", "RL_thigh_joint", "RL_calf_joint", 
    "RR_hip_joint", "RR_thigh_joint", "RR_calf_joint", 
    "waist",  "shoulder", "elbow", "wrist_angle", "wrist_rotate"
  ]  # pinocchio order
  joint_des_pos: [0., 0.75, -1.5, 
                  0., 0.75, -1.5, 
                  0., 0.75, -1.5, 
                  0., 0.75, -1.5, 
                  0., -0.7, 1.3, -0.6, 0.]
  joint_des_vel: [0., 0., 0., 
                  0., 0., 0., 
                  0., 0., 0., 
                  0., 0., 0., 
                  0., 0., 0., 0., 0.]

  joint_kp: [70., 70., 70., 
             70., 70., 70., 
             70., 70., 70., 
             70., 70., 70., 
             10., 10., 10., 10., 10.]
  joint_kd: [7., 7., 7., 
             7., 7., 7., 
             7., 7., 7., 
             7., 7., 7., 
             1., 1., 1., 1., 1.]