################################################################################
# robot configs
################################################################################
sim_robot_variables:
  urdf_filename: "/models/Aliengo/Aliengo.urdf"

  use_fixed_base: False

  base_name: "trunk"
  joint_names: [
    "FL_hip_joint", "FL_thigh_joint", "FL_calf_joint", 
    "FR_hip_joint", "FR_thigh_joint", "FR_calf_joint", 
    "RL_hip_joint", "RL_thigh_joint", "RL_calf_joint", 
    "RR_hip_joint", "RR_thigh_joint", "RR_calf_joint", 
  ]  # pinocchio order
  limb_names: ["FL", "FR", "RL", "RR"]
  limb_endeff_names: ["FL_foot", "FR_foot", "RL_foot", "RR_foot"]

  base_init_pos: [0., 0., 0.40, 0., 0., 0., 1.] # posture
  base_init_vel: [0., 0., 0., 0., 0., 0.]
  joint_init_pos: [0., 0.75, -1.5, 
                   0., 0.75, -1.5, 
                   0., 0.75, -1.5, 
                   0., 0.75, -1.5,]
  joint_init_vel: [0., 0., 0., 
                   0., 0., 0., 
                   0., 0., 0., 
                   0., 0., 0.,]


################################################################################
# control configs
################################################################################
control_variables:
  joint_names: [
    "FL_hip_joint", "FL_thigh_joint", "FL_calf_joint", 
    "FR_hip_joint", "FR_thigh_joint", "FR_calf_joint", 
    "RL_hip_joint", "RL_thigh_joint", "RL_calf_joint", 
    "RR_hip_joint", "RR_thigh_joint", "RR_calf_joint", 
  ]  # pinocchio order
  joint_des_pos: [0., 0.75, -1.5, 
                  0., 0.75, -1.5, 
                  0., 0.75, -1.5, 
                  0., 0.75, -1.5,]
  joint_des_vel: [0., 0., 0., 
                  0., 0., 0., 
                  0., 0., 0., 
                  0., 0., 0.,]
  joint_kp: [70, 70, 70, 
             70, 70, 70, 
             70, 70, 70, 
             70, 70, 70,]
  joint_kd: [3, 3, 3, 
             3, 3, 3, 
             3, 3, 3, 
             3, 3, 3,]